import Head from 'next/head'
import React, { useEffect, useState } from 'react'

import { Footer } from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'
import { Main } from '@/components/Main/Main'
import styles from '@/styles/Home.module.css'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  const [count, setCount] = useState<number>(0)

  // const handleClick = (e: React.MouseEvent<HTMLElement>) => {
  const handleClick = () => {
    setCount(count => count + 1)
  }

  useEffect(() => {
    document.body.style.backgroundColor = 'lightblue'
    return () => {
      document.body.style.backgroundColor = ''
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <button onClick={handleClick}>ボタン</button>
      <h1>{count}</h1>
      <Main title="index" />
      <Footer />
    </div>
  )
}

export default Home
