import Head from 'next/head'
import React from 'react'

import { Footer } from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'
import { Main } from '@/components/Main/Main'
import styles from '@/styles/Home.module.css'
import type { ExtendedNextPage } from '@/types'

const Home: ExtendedNextPage = props => {
  console.log(props)

  const { handleClick, isShow, text, array, handleChange, handleAdd, doubleCount } = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Create App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className={styles.container}>
        <button onClick={handleClick}>ボタン</button>
        <input type="text" value={text} onChange={handleChange}></input>
        <button onClick={handleAdd}>追加</button>
        {isShow ? <h1>{doubleCount}</h1> : null}
        <ul>
          {array.map(item => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      </div>
      <Main title="index" />
      <Footer />
    </div>
  )
}

export default Home
