import Head from 'next/head'
import { useRouter } from 'next/router'

import { Header } from '@/components/Header/Header'
import { PostsByUserId } from '@/components/Posts/PostsByUserId'
import { useCommentInfo } from '@/hooks/usePosts'
import styles from '@/styles/Home.module.css'
import type { ExtendedNextPage } from '@/types'

const UseComment = () => {
  const router = useRouter()
  const { data, error, isLoading } = useCommentInfo(router.query.id ? router.query.id : null)
  if (isLoading) {
    return <div>ローディング中</div>
  }
  if (error) {
    return <div>{error.message}</div>
  }
  return (
    <div>
      <h1>{data.body}</h1>
      <p>{data.name}</p>
      <p>{data.email}</p>
      <h2>元の記事</h2>
      <PostsByUserId id={data.id} />
    </div>
  )
}

const CommentsId: ExtendedNextPage = props => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <UseComment />
    </div>
  )
}

export default CommentsId
