import Head from 'next/head'
import Link from 'next/link'

import { Header } from '@/components/Header/Header'
import { useUsers } from '@/hooks/usePosts'
import styles from '@/styles/Home.module.css'
import type { ExtendedNextPage } from '@/types'

type user = {
  id: number
  name: string
  email: string
}

const UserComponent = () => {
  const { data, error, isLoading, isEmpty } = useUsers()
  if (isLoading) {
    return <div>ローディング中</div>
  }
  if (error) {
    return <div>{error.message}</div>
  }
  if (isEmpty) {
    return <div>データは空です</div>
  }
  return (
    <ol>
      {data.map((user: user) => {
        return (
          <li key={user.id}>
            <Link href={`/users/${user.id}`}>
              <a>{`${user.name} / email : ${user.email}`}</a>
            </Link>
          </li>
        )
      })}
    </ol>
  )
}

const Users: ExtendedNextPage = props => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <UserComponent />
    </div>
  )
}

export default Users
